### PR TITLE
Import PropTypes from prop-types

### PR DESCRIPTION
**Pull request by lorin**
Fixes https://github.com/meteor/simple-todos-react/issues/51

### CODE REVIEW

**Review by bplus — APPROVED** [review]

**Review by MrAlexLau — APPROVED** [review]
Was going through the tutorial just now and noticed this issue. Came here to make this change but saw it's already fixed in this PR!

**Review by tom-gerken — APPROVED** [review]

**Comment by jmporchet** [comment]
@bplus or @MrAlexLau could you please merge this PR as it's important in order to follow the tutorial?
Thanks, your users 😃

**Comment by MrAlexLau** [comment]
@jmporchet - would love to but I don't have write permissions for this repo. Maybe @stubailo can help?

**Comment by jmporchet** [comment]
@MrAlexLau right sorry, I saw you in the reviewers list and I assumed you had write access, my bad!

**Comment by lorin** [comment]
@hwilson Do you know what happened to this PR? Originally it was a single commit.

**Comment by hwillson** [comment]
@lorin Yes - I'm working on updating the entire React tutorial. Unfortunately due to the way this repo is setup, updating individual step commits means a lot of rebasing (under the root commit) and force pushing. This leads to confusing historical changes like the updates you've seen here. This also makes it very difficult to accept PR's into this repo directly unfortunately. I'm updating the full React tutorial from beginning to end, so a lot of the submitted issues/PR's will be closed soon. We're also looking into moving all of the tutorials into a newer, easier to maintain (and accept PR's) infrastructure. Thanks for your help and patience!

**Pull request closed without merging**
